# Generated by Django 3.0.1 on 2019-12-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPChaos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=16)),
                ('cidr', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='IPUnpacked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipunpack', models.CharField(max_length=16)),
            ],
        ),
    ]
