# Generated by Django 3.0.1 on 2019-12-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipconverter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipchaos',
            old_name='cidr',
            new_name='string',
        ),
        migrations.RemoveField(
            model_name='ipchaos',
            name='ip',
        ),
        migrations.AddField(
            model_name='ipchaos',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ipunpacked',
            name='ipunpack',
            field=models.CharField(max_length=50),
        ),
    ]
